language: python
python:
  - "3.3"
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libxml2-dev libxslt1-dev python-dev
install:
  - pip install coveralls
  - pip install -r requirements.txt
script: nosetests -v -s  --with-coverage --cover-package=scrappers --cover-package=server tests/
after_success: coveralls