language: python
sudo: true
python:
  - "3.3"
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libxml2-dev libxslt1-dev python-dev libblas-dev liblapack-dev libatlas-base-dev gfortran
install:
  - pip install coveralls
  - pip install -r requirements-dev.txt
  - python -m nltk.downloader -d nltk_data punkt
env:
  - OPENEWS_DEVELOPMENT_ENV=true
script: nosetests -v -s  --with-coverage --cover-package=scrappers --cover-package=server --cover-package=language tests/
after_success: coveralls