language: python
sudo: true
python:
  - "3.3"
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libxml2-dev libxslt1-dev python-dev libblas-dev liblapack-dev libatlas-base-dev gfortran
install:
  - pip install coveralls
  - travis_wait pip install -r requirements.txt
env:
  - OPENEWS_DEVELOPMENT_ENV=true
script: nosetests -v -s  --with-coverage --cover-package=scrappers --cover-package=server tests/
after_success: coveralls